In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder

In [2]:
!gdown --id 1Yg4UMLgJ2yN7DfeI62-krS_l-_8eUeLK

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1Yg4UMLgJ2yN7DfeI62-krS_l-_8eUeLK
To: /content/verim.csv
100% 7.73k/7.73k [00:00<00:00, 12.6MB/s]


In [3]:
dataset = pd.read_csv("verim.csv",encoding = 'ISO-8859-1')

In [4]:
dataset.head

<bound method NDFrame.head of        Numara Cinsiyet  Yas   Gelir  AlimDurumu
0    15669656    Erkek   31   18000           0
1    15581198    Erkek   31   74000           0
2    15729054    Kadýn   27  137000           1
3    15573452    Kadýn   21   16000           0
4    15776733    Kadýn   28   44000           0
..        ...      ...  ...     ...         ...
278  15717560    Kadýn   38   65000           0
279  15629739    Kadýn   47   51000           1
280  15729908    Erkek   47  105000           1
281  15716781    Kadýn   41   63000           0
282  15646936    Erkek   53   72000           1

[283 rows x 5 columns]>

In [5]:
one_hot = OneHotEncoder(handle_unknown='ignore')
one_hot_cinsiyet = one_hot.fit_transform(dataset['Cinsiyet'].values.reshape(-1,1)).toarray()
one_hot_cinsiyet

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.

In [6]:
one_hot.categories_

[array(['Erkek', 'Kadýn'], dtype=object)]

In [7]:
one_hot_df = pd.DataFrame(one_hot_cinsiyet, columns = one_hot.categories_)
one_hot_df.head()

Erkek Kadýn
0   1.0   0.0
1   1.0   0.0
2   0.0   1.0
3   0.0   1.0
4   0.0   1.0

In [8]:
one_hot_dfjoin = dataset.join(one_hot_df)
one_hot_dfjoin.head()

Numara Cinsiyet  Yas   Gelir  AlimDurumu  (Erkek,)  (Kadýn,)
0  15669656    Erkek   31   18000           0       1.0       0.0
1  15581198    Erkek   31   74000           0       1.0       0.0
2  15729054    Kadýn   27  137000           1       0.0       1.0
3  15573452    Kadýn   21   16000           0       0.0       1.0
4  15776733    Kadýn   28   44000           0       0.0       1.0

In [9]:
one_hot_dfjoin.drop("Cinsiyet", axis=1, inplace= True)
one_hot_dfjoin.head()

Numara  Yas   Gelir  AlimDurumu  (Erkek,)  (Kadýn,)
0  15669656   31   18000           0       1.0       0.0
1  15581198   31   74000           0       1.0       0.0
2  15729054   27  137000           1       0.0       1.0
3  15573452   21   16000           0       0.0       1.0
4  15776733   28   44000           0       0.0       1.0

In [10]:
X = one_hot_dfjoin.drop("AlimDurumu",axis=1)
y=  one_hot_dfjoin["AlimDurumu"]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size =0.3,random_state= 1)

In [13]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [14]:
xx= MinMaxScaler()
x_train = xx.fit_transform(x_train)
x_test = xx.transform(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['str', 'tuple']. An error will be raised in 1.2.
  FutureWarning,


In [15]:
x_train

array([[0.9314388 , 0.28571429, 0.34814815, 0.        , 1.        ],
       [0.01883499, 0.11904762, 0.35555556, 1.        , 0.        ],
       [0.04494921, 0.45238095, 0.97037037, 0.        , 1.        ],
       [0.29300533, 0.38095238, 0.42222222, 0.        , 1.        ],
       [0.83019141, 0.0952381 , 0.08888889, 0.        , 1.        ],
       [0.16362538, 0.80952381, 0.17037037, 0.        , 1.        ],
       [0.780763  , 0.0952381 , 0.2962963 , 0.        , 1.        ],
       [0.20276776, 0.69047619, 0.20740741, 1.        , 0.        ],
       [0.08967922, 0.11904762, 0.37777778, 0.        , 1.        ],
       [0.62440443, 0.52380952, 0.44444444, 0.        , 1.        ],
       [0.90048142, 0.66666667, 0.32592593, 1.        , 0.        ],
       [0.1304801 , 0.97619048, 0.5037037 , 0.        , 1.        ],
       [0.51273864, 0.66666667, 0.05185185, 0.        , 1.        ],
       [0.97761225, 0.19047619, 0.        , 1.        , 0.        ],
       [0.28716954, 0.0952381 , 0.

In [16]:
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [17]:
y_pred = model.predict(x_test)

In [18]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [19]:
confusion_matrix(y_true=y_test, y_pred =y_pred)

array([[63,  3],
       [ 9, 10]])

In [20]:
print(classification_report (y_true=y_test, y_pred = y_pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.91        66
           1       0.77      0.53      0.62        19

    accuracy                           0.86        85
   macro avg       0.82      0.74      0.77        85
weighted avg       0.85      0.86      0.85        85



In [21]:
print ("dogruluk  değeri:", accuracy_score (y_true=y_test, y_pred = y_pred))

dogruluk  değeri: 0.8588235294117647
